import { Comment } from './comments/Comment';

export let data : Array<Comment>= [{
    postId: 6,
    id: 28,
    name: "quo voluptates voluptas nisi veritatis dignissimos dolores ut officiis",
    email: "Ronny@rosina.org",
    body: "voluptatem repellendus quo alias at laudantium mollitia quidem esse temporibus consequuntur vitae rerum illum id corporis sit id",
},
{
    postId: 6,
    id: 29,
    name: "eum distinctio amet dolor",
    email: "Jennings_Pouros@erica.biz",
    body: "tempora voluptatem est magnam distinctio autem est dolorem et ipsa molestiae odit rerum itaque corporis nihil nam eaque rerum error",
},
{
    postId: 6,
    id: 30,
    name: "quasi nulla ducimus facilis non voluptas aut",
    email: "Lurline@marvin.biz",
    body: "consequuntur quia voluptate assumenda et autem voluptatem reiciendis ipsum animi est provident earum aperiam sapiente ad vitae iste accusantium aperiam eius qui dolore voluptatem et",
},
{
    postId: 7,
    id: 31,
    name: "ex velit ut cum eius odio ad placeat",
    email: "Buford@shaylee.biz",
    body: "quia incidunt ut aliquid est ut rerum deleniti iure est ipsum quia ea sint et voluptatem quaerat eaque repudiandae eveniet aut",
},
{
    postId: 7,
    id: 32,
    name: "dolorem architecto ut pariatur quae qui suscipit",
    email: "Maria@laurel.name",
    body: "nihil ea itaque libero illo officiis quo quo dicta inventore consequatur voluptas voluptatem corporis sed necessitatibus velit tempore rerum velit et temporibus",
},
{
    postId: 7,
    id: 33,
    name: "voluptatum totam vel voluptate omnis",
    email: "Jaeden.Towne@arlene.tv",
    body: "fugit harum quae vero libero unde tempore soluta eaque culpa sequi quibusdam nulla id et et necessitatibus",
},
{
    postId: 7,
    id: 34,
    name: "omnis nemo sunt ab autem",
    email: "Ethelyn.Schneider@emelia.co.uk",
    body: "omnis temporibus quasi ab omnis facilis et omnis illum quae quasi aut minus iure ex rem ut reprehenderit in non fugit",
},
{
    postId: 7,
    id: 35,
    name: "repellendus sapiente omnis praesentium aliquam ipsum id molestiae omnis",
    email: "Georgianna@florence.io",
    body: "dolor mollitia quidem facere et vel est ut ut repudiandae est quidem dolorem sed atque rem quia aut adipisci sunt",
},
{
    postId: 8,
    id: 36,
    name: "sit et quis",
    email: "Raheem_Heaney@gretchen.biz",
    body: "aut vero est dolor non aut excepturi dignissimos illo nisi aut quas aut magni quia nostrum provident magnam quas modi maxime voluptatem et molestiae",
},
{
    postId: 8,
    id: 37,
    name: "beatae veniam nemo rerum voluptate quam aspernatur",
    email: "Jacky@victoria.net",
    body: "qui rem amet aut cumque maiores earum ut quia sit nam esse qui iusto aspernatur quis voluptas dolorem distinctio ex temporibus rem",
},
{
    postId: 8,
    id: 38,
    name: "maiores dolores expedita",
    email: "Piper@linwood.us",
    body: "unde voluptatem qui dicta vel ad aut eos error consequatur voluptatem adipisci doloribus qui est sit aut velit aut et ea ratione eveniet iure fuga",
},
{
    postId: 8,
    id: 39,
    name: "necessitatibus ratione aut ut delectus quae ut",
    email: "Gaylord@russell.net",
    body: "atque consequatur dolorem sunt adipisci autem et voluptatibus et quae necessitatibus rerum eaque aperiam nostrum nemo eligendi sed et beatae et inventore",
}]